runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_conifg:
  python_version: 3.6
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
  target_concurrent_requests: 100
resources:
    cpu: 1
    memory_gb: 0.9
    disk_size_gb: 10
liveness_check:
  check_interval_sec: 80
  timeout_sec: 60
  failure_threshold: 2
  success_threshold: 2    
    
