runtime: python
env: flex
entrypoint: gunicorn -b :$port app:app

runtime_conifg:
  python_version: 3.6
  
manual_scaling:
  instances: 1
resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10
